version: '3'
services:
  tomcat: 
    image: tomcat
    container_name: tomcat
    ports: 
      - 8080:8080
    restart: always
    depends_on: 
      - db
  db:  
    image: postgres
    container_name: postgres
    ports: 
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRRES_DB: Zhaludkovich
    restart: always
  web1:
    build: .
  web2: 
    build: .
  web3: 
    build: .
  web4: 
    build: .
  web5: 
    build: .



