# This is a basic workflow to help you get started with Actions

name: MyFirstAction
env: 
  DEPlOY_VER    : "${{ github.sha }}"
  YEAR          : "2022"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  FirstJOB:
    runs-on: ubuntu-latest
    steps:
     
     - name: Clone repo GITHUB
       uses: actions/checkout@v1
     
     - name: List file in folder
       run: ls -la
       
     - name: Content from log.txt
       run: cat log.txt
       
     - name: Print Hello from SHA
       run: echo "Hello from ${{ env. DEPlOY_VER }}"

